const stateKey='opsdrill-v7';
const state=JSON.parse(localStorage.getItem(stateKey)||'{"done":[],"bookmarks":[],"filter":"Beginner","search":"","topic":"Azure"}');
let questions=[];
const topicMeta={
 Azure:['☁️','01','Azure fundamentals → networking → identity → monitoring → architecture'],
 Kubernetes:['⎈','02','Containers → workloads → networking → scaling → production'],
 Terraform:['🏗️','03','IaC basics → resources → state → modules → production'],
 Docker:['🐳','04','Images → containers → networking → security → optimization'],
 'CI/CD':['🚀','05','Git flow → pipelines → tests → artifacts → deployment strategy'],
 Linux:['⌁','06','Shell → filesystem → processes → networking → troubleshooting'],
 DevSecOps:['🛡️','07','Security basics → scanning → secrets → supply chain → governance'],
 Git:['🌿','08','Git basics → branches → history → collaboration → recovery'],
 Jenkins:['⚙️','09','Jenkins basics → pipelines → agents → credentials → scale'],
 'GitHub Actions':['◉','10','Workflows → jobs → runners → artifacts → secure delivery'],
 Ansible:['▣','11','Inventory → playbooks → variables → roles → automation'],
 Networking:['⌁','12','OSI → TCP/IP → DNS → routing → troubleshooting'],
 Monitoring:['📈','13','Metrics → logs → traces → Prometheus → Grafana → SLOs'],
 AWS:['☁️','14','Cloud basics → IAM → VPC → compute → managed services'],
 SRE:['🛡️','15','SLI → SLO → error budgets → incidents → reliability'],
 'System Design':['◈','16','Requirements → scale → architecture → resilience → trade-offs']
};
const stages=[
 ['Beginner','01 · Foundation','Learn the vocabulary, purpose and basic commands first.'],
 ['Intermediate','02 · Core Skills','Understand how components connect and how to use them correctly.'],
 ['Advanced','03 · Production','Troubleshoot incidents, security, performance and operational risks.'],
 ['Senior','04 · Architecture','Handle design, scale, trade-offs, reliability and leadership follow-ups.']
];
function save(){localStorage.setItem(stateKey,JSON.stringify(state))}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function pct(){return questions.length?Math.round(state.done.filter(id=>questions.some(q=>q.id===id)).length/questions.length*100):0}
function loadScript(src){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src+(src.includes('?')?'&':'?')+'v=20260823-2';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
async function init(){try{if(!window.OPSDRILL_MASTER)await loadScript('content/master-bank.js');if(!window.OPSDRILL_BANK)await loadScript('content/question-bank.js');const r=await fetch('content/questions.json?v=20260823-2');const base=await r.json();questions=[...base,...(window.OPSDRILL_BANK||[]),...(window.OPSDRILL_MASTER||[])].filter((q,i,a)=>a.findIndex(x=>x.id===q.id)===i)}catch(e){console.error(e);questions=[...(window.OPSDRILL_BANK||[]),...(window.OPSDRILL_MASTER||[])]}render()}
function stageOf(q){return q.level==='Beginner'?'Beginner':q.level==='Intermediate'?'Intermediate':q.level==='Senior'?'Senior':'Advanced'}
function ordered(list){const rank={Beginner:1,Intermediate:2,Advanced:3,Senior:4};const typeRank={Concept:1,Compare:2,Scenario:3,Troubleshooting:4,Production:5,Security:6,Optimization:7,Design:8,Senior:9};return [...list].sort((a,b)=>(rank[stageOf(a)]-rank[stageOf(b)])||(typeRank[a.type]||10)-(typeRank[b.type]||10)||a.id.localeCompare(b.id))}
function counts(topic){const qs=questions.filter(q=>q.topic===topic);return {all:qs.length,beginner:qs.filter(q=>q.level==='Beginner').length,intermediate:qs.filter(q=>q.level==='Intermediate').length,advanced:qs.filter(q=>q.level==='Advanced').length,senior:qs.filter(q=>q.level==='Senior').length}}
function render(){const active=state.topic;const c=active?counts(active):null;document.getElementById('app').innerHTML=`
<header class="topbar"><div class="container nav"><button class="logo" onclick="home()">Ops<span>Drill</span></button><nav class="navlinks"><button onclick="go('roadmap')">Roadmap</button><button onclick="go('topics')">Topics</button><button onclick="go('practice')">Practice</button><button onclick="openMock()">Mock Interview</button></nav><button class="btn secondary" onclick="openMock()">Start →</button></div></header>
<main class="container">
<section class="hero"><div class="eyebrow">Structured DevOps interview platform</div><h1>Learn in order.<br><span>Answer like production.</span></h1><p>OpsDrill starts with fundamentals and progressively moves into real incidents, security, troubleshooting and senior architecture. Every answer uses Story → Hinglish → English → Deep Dive → Production.</p><div class="actions"><button class="btn primary" onclick="startBasics()">Start from basics</button><button class="btn secondary" onclick="go('topics')">Browse all tracks</button></div><div class="stats"><div class="stat"><strong>${questions.length}</strong><small>total questions</small></div><div class="stat"><strong>${questions.filter(q=>q.type==='Scenario').length}</strong><small>scenario drills</small></div><div class="stat"><strong>${pct()}%</strong><small>mastered</small><div class="progress"><i style="width:${pct()}%"></i></div></div><div class="stat"><strong>16</strong><small>ordered learning tracks</small></div></div></section>
<section class="section" id="roadmap"><div class="section-head"><div><div class="eyebrow">Learning path</div><h2>Do not jump to advanced yet</h2><p class="sub">Follow the same progression you would use on a real DevOps journey.</p></div></div><div class="roadmap">${stages.map((s,i)=>`<article class="phase"><div class="phase-no">${i+1}</div><div><span class="phase-tag">${s[0]}</span><h3>${s[1]}</h3><p>${s[2]}</p></div></article>`).join('')}</div></section>
<section class="section" id="topics"><div class="eyebrow">Curriculum</div><h2>16 tracks, one clear order</h2><p class="sub">Open a track and start at Foundation. Advanced sections stay locked behind the learning order conceptually, not behind your access.</p><div class="topicgrid">${Object.entries(topicMeta).map(([name,m])=>{const x=counts(name);return `<article class="topic ${active===name?'selected':''}" onclick="topic('${name}')"><div class="topic-top"><span class="topic-number">${m[1]}</span><span class="icon">${m[0]}</span></div><h3>${name}</h3><p>${m[2]}</p><div class="level-row"><span>Foundation <b>${x.beginner}</b></span><span>Core <b>${x.intermediate}</b></span><span>Production <b>${x.advanced}</b></span><span>Senior <b>${x.senior}</b></span></div><span class="badge">${x.all} questions</span></article>`}).join('')}</div></section>
<section class="section" id="practice"><div class="practice-head"><div><div class="eyebrow">Current track</div><h2>${esc(active||'Choose a track')}</h2><p class="sub">${active?esc(topicMeta[active][2]):'Choose a topic above to start from Foundation.'}</p></div>${active?`<div class="track-total"><strong>${c.all}</strong><span>questions in this track</span></div>`:''}</div>${active?`<div class="level-path">${[['Beginner','01 Foundation'],['Intermediate','02 Core'],['Advanced','03 Production'],['Senior','04 Architecture']].map(x=>`<button class="path-step ${state.filter===x[0]?'active':''}" onclick="setFilter('${x[0]}')"><b>${x[1]}</b><small>${counts(active)[x[0].toLowerCase()]||0} questions</small></button>`).join('')}</div>`:''}<div class="toolbar"><input class="search" id="search" placeholder="Search within this track..." value="${esc(state.search)}"><button class="filter ${state.filter==='All'?'active':''}" onclick="setFilter('All')">All levels</button><button class="filter ${state.filter==='Scenario'?'active':''}" onclick="setFilter('Scenario')">Scenarios</button><button class="filter ${state.filter==='Troubleshooting'?'active':''}" onclick="setFilter('Troubleshooting')">Troubleshooting</button></div><div id="questionList"></div></section>
<section class="section" id="scenarios"><div class="eyebrow">Production practice</div><h2>Scenario room</h2><p class="sub">Only open this after learning the fundamentals. Think impact → evidence → isolate → mitigate → verify → prevent.</p><div class="scenario-grid">${ordered(questions.filter(q=>q.type==='Scenario')).slice(0,16).map(q=>`<article class="card scenario" onclick="openQuestion('${q.id}')"><span class="tag">${esc(q.topic)} · ${esc(q.level)}</span><h3>${esc(q.question)}</h3><p>Open investigation →</p></article>`).join('')}</div></section>
</main><footer class="footer"><div class="container"><strong>OpsDrill</strong> · Practice DevOps. Think Production.</div></footer><div id="modal" class="modal" onclick="if(event.target===this)closeModal()"><div class="modalbox" id="modalbox"></div></div>`;
const search=document.getElementById('search');if(search)search.addEventListener('input',e=>{state.search=e.target.value;save();renderQuestions()});renderQuestions()}
function home(){state.topic='Azure';state.filter='Beginner';state.search='';save();render();window.scrollTo({top:0,behavior:'smooth'})}
function startBasics(){state.topic='Azure';state.filter='Beginner';state.search='';save();render();setTimeout(()=>go('practice'),80)}
function go(id){document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'})}
function setFilter(f){state.filter=f;save();renderQuestions();go('practice')}
function topic(t){state.topic=t;state.filter='Beginner';state.search='';save();render();go('practice')}
function openQuestion(id){const q=questions.find(x=>x.id===id);if(!q)return;state.topic=q.topic;state.filter=q.level;state.search=q.id;save();render();go('practice')}
function renderQuestions(){const el=document.getElementById('questionList');if(!el)return;const term=state.search.toLowerCase();let list=ordered(questions.filter(q=>q.topic===state.topic));if(term)list=list.filter(q=>Object.values(q).join(' ').toLowerCase().includes(term));if(state.filter!=='All'&&['Beginner','Intermediate','Advanced','Senior'].includes(state.filter))list=list.filter(q=>q.level===state.filter);else if(['Scenario','Troubleshooting'].includes(state.filter))list=list.filter(q=>q.type===state.filter);list=list.slice(0,80);el.innerHTML=list.length?list.map(q=>{const done=state.done.includes(q.id),bm=state.bookmarks.includes(q.id);return `<article class="card question"><div class="qtop"><span class="tag">${esc(q.topic)} · ${esc(stageOf(q))} · ${esc(q.type)}</span><button class="star ${bm?'on':''}" onclick="bookmark('${q.id}')">${bm?'★':'☆'}</button></div><div class="qnumber">Question ${String(questions.filter(x=>x.topic===q.topic).indexOf(q)+1).padStart(3,'0')}</div><h3>${esc(q.question)}</h3><button class="btn secondary reveal" onclick="reveal('${q.id}')">${done?'Review answer':'Reveal answer'}</button><div id="ans-${q.id}"></div></article>`}).join(''):'<div class="card empty"><h3>No questions here yet</h3><p>Try another level or clear the search.</p></div>'}
function reveal(id){const q=questions.find(x=>x.id===id),box=document.getElementById('ans-'+id);if(!q||!box)return;box.innerHTML=`<div class="answer"><div class="answer-grid"><div><h4>📖 Story / Situation</h4><p>${esc(q.question)}</p></div><div><h4>🎯 What interviewer wants</h4><p>Clear fundamentals first, then reasoning, evidence and a safe production decision.</p></div></div><h4>🇮🇳 Simple Hinglish Explanation</h4><p>${esc(q.hinglish)}</p><h4>🇬🇧 Interview-ready English Answer</h4><p>${esc(q.english)}</p><h4>🔍 Deep Dive</h4><p>${esc(q.deep)}</p><h4>💻 Practical Commands</h4><pre>${esc(q.commands)}</pre><h4>🏭 Production Approach</h4><p>${esc(q.production)}</p><h4>⚠️ Common Mistake</h4><p>${esc(q.mistake)}</p><h4>🧠 Senior-Level Insight</h4><p>${esc(q.senior)}</p><div class="followup"><b>🎤 Follow-up:</b> ${esc(q.followup)}</div><br><button class="btn primary" onclick="master('${q.id}')">${state.done.includes(q.id)?'Mastered ✓':'Mark as mastered'}</button></div>`}
function master(id){if(!state.done.includes(id))state.done.push(id);save();renderQuestions()}
function bookmark(id){state.bookmarks=state.bookmarks.includes(id)?state.bookmarks.filter(x=>x!==id):[...state.bookmarks,id];save();renderQuestions()}
function openMock(){document.getElementById('modalbox').innerHTML=`<button class="close" onclick="closeModal()">×</button><div class="eyebrow">Mock interview</div><h2>Choose your level</h2><p class="sub">Start with fundamentals. The mock gets harder as you progress.</p><div class="mockgrid"><button onclick="mock('Beginner')"><b>Foundation</b><br>0–2 years · concepts + commands</button><button onclick="mock('Intermediate')"><b>Core</b><br>2–5 years · implementation + CI/CD</button><button onclick="mock('Advanced')"><b>Production</b><br>3–6 years · incidents + security</button><button onclick="mock('Senior')"><b>Architecture</b><br>5–8+ years · design + trade-offs</button></div>`;document.getElementById('modal').classList.add('open')}
function mock(level){let pool=questions.filter(q=>q.level===level);if(!pool.length)pool=questions;const q=pool[Math.floor(Math.random()*pool.length)];document.getElementById('modalbox').innerHTML=`<button class="close" onclick="closeModal()">×</button><div class="eyebrow">Mock · ${level}</div><span class="tag">${esc(q.topic)} · ${esc(q.type)}</span><h2>${esc(q.question)}</h2><p class="sub">Answer aloud for 60–90 seconds. Then compare with the expected structure.</p><button class="btn primary" onclick="this.nextElementSibling.hidden=false">Reveal expected approach</button><div class="answer" hidden><h4>Expected approach</h4><p>${esc(q.english)}</p><h4>Follow-up</h4><p>${esc(q.followup)}</p><button class="btn secondary" onclick="mock('${level}')">Next question →</button></div>`}
function closeModal(){document.getElementById('modal').classList.remove('open')}
init();
