window.OPSDRILL_STACKS = [
  {
    id:'azure-devops-terraform', number:'01', title:'Azure DevOps + Terraform',
    subtitle:'Azure Infrastructure as Code + CI/CD + enterprise delivery',
    intro:'In my project, I use Terraform to provision Azure infrastructure in a repeatable and version-controlled way, while Azure DevOps handles source control, CI/CD and controlled deployments. The goal is to eliminate manual portal changes and make infrastructure changes reviewable, auditable and consistent across environments.',
    interview:'I worked on an Azure-based DevOps platform where the infrastructure was managed through Terraform and the delivery process was automated using Azure DevOps. I followed Infrastructure as Code, so instead of manually creating Azure resources from the portal, I defined resources in HCL, stored the code in Git, used a remote Terraform backend for state management and ran terraform fmt, validate and plan during CI. After Pull Request review and approval, the pipeline applied the approved plan to the target environment. For production, I separated environments, used service connections or workload identity, protected secrets with Key Vault, added approval gates and kept the deployment auditable. This gave us repeatability, controlled change management and a safer rollback or recovery path.',
    project:'Project: Azure Enterprise Application Landing Zone. Provision Resource Groups, VNet, subnets, NSGs, private endpoints, Key Vault, Azure Storage and application infrastructure using reusable Terraform modules. Azure DevOps YAML pipelines run validation and security checks, publish the Terraform plan as an artifact, require approval for production and execute apply only after approval. Remote state is stored centrally with locking and access control.',
    explain:['Start with requirements and environment separation.','Design the Azure network and identity model before provisioning.','Create reusable Terraform modules and environment-specific tfvars.','Configure a secure remote backend and state locking.','Build Azure DevOps multi-stage YAML pipelines.','Run fmt, validate, plan and security/policy checks in CI.','Review the plan through Pull Request and approval gates.','Apply only the reviewed plan to staging/production.','Monitor the deployment and use rollback/recovery procedures when required.'],
    flow:['Git repository','Terraform modules','Remote backend + state locking','Azure infrastructure','Azure DevOps CI','Plan artifact + security checks','Approval gate','Production apply','Azure Monitor / Log Analytics','Recovery / rollback'],
    terms:['Azure Subscription','Resource Group','VNet','Subnet','NSG','Private Endpoint','Managed Identity','RBAC','Key Vault','Terraform Provider','HCL','tfvars','Remote Backend','State Locking','Module','Plan Artifact','Azure Repos','Azure Pipelines','Service Connection','Variable Group','Environment','Approval Gate'],
    questions:['Why Terraform instead of manually creating Azure resources?','How do you manage Terraform state in a team?','How would you secure secrets in Azure DevOps?','How do you promote Terraform changes from dev to production?','What happens if terraform apply fails halfway?']
  },
  {
    id:'terraform-cicd-git-github', number:'02', title:'Terraform + CI/CD + Git/GitHub',
    subtitle:'Infrastructure as Code + Git workflow + automated delivery',
    intro:'This project demonstrates a complete infrastructure change lifecycle: Git branching and Pull Requests trigger CI, Terraform code is validated and security-checked, a plan is generated as a review artifact, and only an approved change is promoted to the target environment.',
    interview:'In this project, Git and GitHub are the control plane for infrastructure changes. I follow a feature-branch and Pull Request workflow. A developer changes Terraform code, pushes the branch and opens a PR. CI automatically runs terraform fmt, validate, security scanning and terraform plan. The generated plan is stored as an artifact so reviewers can see exactly what infrastructure will change. After review and required checks pass, the PR is merged into the protected main branch. The deployment workflow then uses the approved artifact or generates a controlled plan for the target environment and applies it with protected credentials. I also use remote state, state locking, OIDC where supported, environment protection and audit trails. This reduces configuration drift and prevents unreviewed infrastructure changes from reaching production.',
    project:'Project: GitHub-controlled Terraform Delivery Platform. Developers submit infrastructure changes through Pull Requests. GitHub Actions runs linting, terraform validate, security checks, plan generation and policy validation. The plan is attached to the PR for review. Protected branches and environment approvals control production deployment. Credentials use short-lived OIDC authentication instead of long-lived cloud keys where the platform supports it.',
    explain:['Developer creates a feature branch.','Terraform change is committed and pushed.','Pull Request starts CI automatically.','CI validates syntax and formatting.','Security and policy checks detect risky resources.','terraform plan shows the exact infrastructure delta.','The plan becomes a reviewable artifact.','Required reviewers approve the Pull Request.','Merge to protected main triggers controlled deployment.','Production environment requires an approval gate.'],
    flow:['Feature branch','Pull Request','CI validation','Security / policy scan','terraform plan','Plan artifact','Code review','Protected main','Environment approval','Terraform apply','Audit + drift detection'],
    terms:['Git','Feature Branch','Pull Request','Protected Branch','Merge','Rebase','GitHub Actions','Workflow','Runner','Artifact','OIDC','Secrets','Terraform Plan','Plan Artifact','Remote Backend','State Lock','Drift Detection','Policy as Code','Approval','Environment Protection'],
    questions:['Why use Pull Requests for Terraform?','Why should a Terraform plan be reviewed?','How do you prevent secrets from leaking into GitHub?','What is Terraform drift and how do you detect it?','How would you design dev/stage/prod promotion?']
  },
  {
    id:'docker-kubernetes', number:'03', title:'Docker + Kubernetes',
    subtitle:'Containerization + orchestration + resilient production workloads',
    intro:'This stack shows the application delivery path from source code to a production Kubernetes workload. Docker creates a portable and reproducible image, while Kubernetes handles scheduling, service discovery, rollout, scaling, health checks and workload recovery.',
    interview:'In my project, I containerized the application using Docker and deployed it on Kubernetes. I used a multi-stage Docker build to keep the final image small and excluded unnecessary build dependencies from the runtime image. The image was tagged immutably and pushed to a container registry after security scanning. Kubernetes Deployments managed replica count and rolling updates, Services provided stable internal discovery and Ingress handled external HTTP routing. I defined CPU and memory requests and limits, readiness and liveness probes, ConfigMaps for non-sensitive configuration and Secrets for sensitive values. For production, I used HPA for demand-based scaling and monitored logs and metrics to troubleshoot failures. The focus was not just deploying containers, but making the workload resilient, observable and safely deployable.',
    project:'Project: Production Microservices Platform on Kubernetes. Build services as minimal Docker images, scan them, push immutable image tags/digests to a registry and deploy through Kubernetes Deployments. Use Namespaces for isolation, ConfigMaps/Secrets for configuration, Services for service discovery, Ingress for north-south traffic, readiness/liveness probes for health management, resource requests/limits for scheduling and HPA for autoscaling. Rolling updates and rollback protect application availability.',
    explain:['Create a production-ready Dockerfile.','Use multi-stage builds and a minimal runtime image.','Scan the image before publishing it.','Push the image to a private registry.','Deploy the immutable image to Kubernetes.','Use Deployment and ReplicaSet for desired state and replicas.','Expose workloads with Services and Ingress.','Add probes so Kubernetes can distinguish healthy and unhealthy containers.','Define resource requests and limits for predictable scheduling.','Enable HPA and monitor metrics/logs for production behavior.'],
    flow:['Source code','Dockerfile','Multi-stage build','Image scan','Registry push','Deployment manifest','Pod scheduling','Service discovery','Ingress / Gateway','Readiness + liveness','HPA','Logs / metrics / traces'],
    terms:['Dockerfile','Image Layer','Build Context','Multi-stage Build','ENTRYPOINT','CMD','Registry','Image Digest','Container Runtime','Pod','Deployment','ReplicaSet','Namespace','Service','Ingress','ConfigMap','Secret','Requests / Limits','Readiness Probe','Liveness Probe','HPA','kubectl'],
    questions:['Why use multi-stage Docker builds?','What is the difference between a Docker image and container?','Why do Kubernetes Pods restart?','Readiness vs liveness probe?','How would you troubleshoot CrashLoopBackOff?','How does HPA decide when to scale?']
  }
];